### ISSUE TITLE
hard coded versions that should be compose json

### ISSUE THREAD

**Issue by c-harris** [Algo-Web/POData#1]
the current one that i notice is the POData/src/POData/OperationContext/Web/Illuminate/ folder This is clearly taken from another package, and i feel like we should update composer json to get the package instead of copying the code out.

**Comment by CyberiaResurrection** [comment]
Feel a bit dumb letting this one go so long - not long after fork time, I ripped out most of the upstream baggage and repointed the request wrapper to use the composer package version of illuminate/http.
