### ISSUE TITLE
C(R)UD support?

### ISSUE THREAD

**Issue by tmikaeld** [Algo-Web/POData#137]
Is this library ready for usage?

**Comment by c-harris** [comment]
It is mostly ready for use, it currently has limited crud support to create and update primitive properties but the capacity to create complex objects and/or associations is not complete, we should be rolling out a release the middle of next month that would provide that capacity. delete is working fine.

**Comment by tmikaeld** [comment]
Thanks for the quick response!

I checked the Doc and it seems pretty straightforward, but i noticed it's 5 years old, a lot have happened since then?

My goal is to consume MS Dynamics NAV pages using OData instead of the (horrible) SOAP that I'm using now.

**Comment by CyberiaResurrection** [comment]
The upstream that we branched from is pretty moribund, but we've been cleaning out and straightening up the codebase so we can use it ourselves.  Heaps has happened, and I'm curious how someone who isn't a maintainer (ie, myself or @c-harris) goes with using it.
