### ISSUE TITLE
JSON payload no longer accepted in POST/PUT

### ISSUE THREAD

**Issue by cdcampos** [Algo-Web/POData#192]
After changes in version 0.3.0, JSON formed data sent in payload is no longer accepted. Failure occurs in executePost() and executePut() methods of URIProcessorNew.

Root cause seems to be missing implementation of deserialization of data into an instance of ODataEntry in readData() of RequestDescription.

**Comment by CyberiaResurrection** [comment]
Thanks for chasing this down and localising it - and thanks again for catching a JSON goof we made.

What's got me a bit puzzled is that there is json deserialisation stuff there - so why is it not, according to your report, getting called?

Could you try adding a dd($data) call just after line 321 of RequestDescription and re-trying your JSON request, to see if it even gets that far?

**Comment by cdcampos** [comment]
After line 321 of RequestDescription $data contains an array. This is the result of json_decode.

My payload containing: 
> {"Utilizador":"carlos"}

results in $data having (output of dd($data)):
> array(1) { ["Utilizador"]=> string(6) "carlos" }

But in executePost() and executePut() of URIProcessorNew warnings come from asserts verifying that the data is an instance of ODataEntry. After the warnings fatal error occurs as an array cannot be used to proceed:

> <b>Warning</b>:  get_class() expects parameter 1 to be object, array given in <b>C:\www\GEA\vendor\algo-web\podata\src\POData\UriProcessor\UriProcessorNew.php</b> on line <b>372</b><br />

> <b>Warning</b>: assert():  failed in <b>C:\www\GEA\vendor\algo-web\podata\src\POData\UriProcessor\UriProcessorNew.php</b> on line <b>372</b><br />

> <b>Fatal error</b>:  Uncaught TypeError: Argument 2 passed to POData\ObjectModel\ModelDeserialiser::bulkDeserialise() must be an instance of POData\ObjectModel\ODataEntry, array given, called in C:\www\GEA\vendor\algo-web\podata\src\POData\UriProcessor\UriProcessorNew.php on line 374 and defined in C:\www\GEA\vendor\algo-web\podata\src\POData\ObjectModel\ModelDeserialiser.php:29

**Comment by CyberiaResurrection** [comment]
Thanks for correcting my mistaken assumption.  ~~This will probably take more work than your other bug report to chase down and fix.~~

The asserts are there and doing what they should - codifying invariants and breaking loudly when violated - but as you've pointed out, serialisation needs to be common to both parts.

This looks to be blast damage from when we ran through POData's internals and encapsulated things that were passed around so we could use lots more type hints and give static analysis (such as Scrutinizer) more traction.

**Comment by c-harris** [comment]
This issue has been addressed by #227 and is being further looked into in #271 as such I am closing
