### ISSUE TITLE
Not possible to assign a custom name to Resource Set

### ISSUE THREAD

**Issue by cdcampos** [Algo-Web/POData#193]
When calling addResourceSet() in SimpleMetadataProvider, first parameter is the name of Entity Set being added. This parameter is now ignored (from version 0.3.0) and Entity Set name is always the result of Str::plural over Entity Type name.

This behavior is quite annoying when Entity names are not in English, using Illuminate\Support\Str (to my knowledge currently only supporting English) on non English words is wrong.

Of course this is not a bug, but to avoid changing the names of all my constructs (in Portuguese language...), is there any possibility to enable again the use of first parameter in addResourceSet()?

**Comment by CyberiaResurrection** [comment]
cdcampos, thanks for taking the time to grab our recent changes and report this issue.

Both @c-harris  and I are native English speakers, so this flat-out didn't occur to us as a problem.  Thanks for the catch and narrowing down where we broke it.

Looking at it now, I'm thinking simplest fix would be to flip the arguments in the interface definition, make $name an optional parameter, and apply the Str::plural route if and only if $name is null.

Can you see any simpler way to fix this issue?

**Comment by cdcampos** [comment]
I think that would be a good solution yes 👍

**Comment by CyberiaResurrection** [comment]
I wanted to double-check with you before I did something silly, like implement a half-baked "fix" that didn't actually help you.

Out of curiosity, would you be able to send in a pull request that fixes this issue?  Thanks to your help, it's extremely well-characterised (even to the wombat (me) who broke it in first place ).

If you need help with adding tests to verify that things work as you expect they should, I can definitely help you there - I've (re)written vast bulk of POData's test suite.

**Comment by cdcampos** [comment]
I can't send the pull request, not versed in using git.

I guess the fix here is not restricted to addResourceSet() code, right?
I have made a search for Str::plural and seems to be used to retrieve the set name (examples ODataEntry->setType, SegmentParser->createFirstSegmentDescriptor, as well as MetadataManager in o-data-metadata).

**Comment by CyberiaResurrection** [comment]
Was worth a shot asking if you could send the pull request - oh well.  It's not like I have any NEED to hog credit - I want to share it around.

No, it's certainly not restricted to the original case you tripped over - the more that get found, the more can be fixed.

My first impressions (please refute these if you can):
ODataEntry->setType seems to be a little trickier- may need a metadata lookup to dig out authoritative resource name.
SegmentParser->createFirstSegmentDescriptor - not sure - may need to extend ResourceType to have a getSetName function and have that passed in during construction.
The three instances in MetadataManager in o-data-metadata also look like they need to be cut over to a lookup of some sort.

**Comment by CyberiaResurrection** [comment]
I think I've fixed it in #195 for addResourceSet case, as well as createFirstSegmentDescriptor case (tests blew up real good on that one).
@cdcampos, can you double-check when you get a chance - especially the tests I added to make sure of things?

**Comment by cdcampos** [comment]
Your changes so far look good.

**Comment by CyberiaResurrection** [comment]
Tweaked issue title slightly to better reflect problem - you might be working in English, (and thus not have a problem with existing, baked-in, assumption), and for whatever reason, you may well need to assign a custom name (such as in test case I've attached in pull request)

**Comment by CyberiaResurrection** [comment]
I think that #195 fixes this issue - for moment, you have to supply the custom resource set name twice - once when adding the resourceEntityType (refClass, name, pluralName) and again when adding the ResourceSet.

**Comment by cdcampos** [comment]
Tested on my side, working as expected!

**Comment by CyberiaResurrection** [comment]
Sweet!  Thank you for your patience, feedback, and testing.
