### ISSUE TITLE
Error writing JSON output

### ISSUE THREAD

**Issue by cdcampos** [Algo-Web/POData#196]
When building JSON response an error occurs in quoteJScriptString of JsonWriter:
> Catchable fatal error: Object of class POData\ObjectModel\ODataCategory could not be converted to string in C:\www\GPC\vendor\algo-web\podata\src\POData\Writers\Json\JsonWriter.php on line 187

**Comment by CyberiaResurrection** [comment]
Thanks for reporting this - it looks like that's been fixed in #194 - can you go through that bit of change and double-check for me?

**Comment by CyberiaResurrection** [comment]
Fixed specifically in #197 - along with a bug in JsonLightODataWriter, which I flattened because I was in neighbourhood.

@cdcampos , can you update at your end and check that this particular problem is now fixed?

**Comment by cdcampos** [comment]
I confirm this is fixed 👍
