### ISSUE TITLE
Missing namespace in metadata info for a result entry

### ISSUE THREAD

**Issue by cdcampos** [Algo-Web/POData#199]
In the metadata info sent inline with the results in JSON format the referenced type is not qualified with metadata namespace.

Incorrect output (from version 0.3.0):
> ` __metadata": {
            "uri":"http://localhost//AlgoWebPOData/odata.svc/Sessoes(ID=1)","type":"Sessao" }`

Correct output (before version 0.3.0):
> ` __metadata": {
            "uri":"http://localhost//AlgoWebPOData/odata.svc/Sessoes(ID=1)","type":"OData.Sessao" }`

**Comment by c-harris** [comment]
ok, looks like I got the short straw (Because I am awake) but important question with this one is what kinda of end point is this at? (metadata, collection, single record)

**Comment by cdcampos** [comment]
This occurs in every JSON formatted GET request for collection or single record. I think the issue is related to the changes in writeEntryMetadata of JsonODataV1Writer, lines 193-199, where "type" within "__metadata" property is written. Before version 0.3.0 $entry->type had the full entity type name (preceded with the namespace), in current version namespace is not present in $entry->type.

**Comment by cdcampos** [comment]
I have changed the title in the issue, as I figured this is not a JSON specific problem. Also in ATOM output the attribute "term" in "category" element comes with missing namespace:
`<category term="Sessao" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/>`

it should be instead:
`<category term="OData.Sessao" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/>`

**Comment by c-harris** [comment]
ok, I am fairly sure i know what the issue is here and how to fix it but spent most of today tracking down a different one. hopefully i can get this sorted before the new year

**Comment by c-harris** [comment]
@cdcampos could i perhaps steal your attention over here
https://github.com/Algo-Web/POData/issues/202

**Comment by CyberiaResurrection** [comment]
Looks like getFullName is being correctly called by CynicSerialiser, but actual returned value is not fully-qualified (as in @cdcampos' example, Sessao vs OData.Sessao).  ResourceType awaits!

**Comment by CyberiaResurrection** [comment]
G'day Carlos,

I think I've fixed this in #207 - could you composer update and check if I have?

**Comment by cdcampos** [comment]
Yes, you have, good!
