### ISSUE TITLE
Missing output when $expand results are empty

### ISSUE THREAD

**Issue by cdcampos** [Algo-Web/POData#203]
When $expand clause is used to deliver a set and provider does not send any results the output of an empty set is missing (as if the $expand was not used at all).

For this request: odata.svc/Tabelas('S_Anexos')?$expand=CamposChave

In atom output this is the output of an empty navigation to a set:
`<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/CamposChave" type="application/atom+xml;type=feed" title="CamposChave" href="Tabelas(ID='S_Anexos')/CamposChave"/>`

But it should be this:
```
<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/CamposChave" type="application/atom+xml;type=feed" title="CamposChave" href="Tabelas(ID='S_Anexos')/CamposChave">
<m:inline>
   <feed>
    <title type="text">CamposChave</title>
    <id>http://localhost//GPC/odata.svc/Tabelas(ID='S_Anexos')/CamposChave</id>
    <updated>2018-01-02T08:23:10+00:00</updated>
    <link rel="self" title="CamposChave" href="Tabelas(ID='S_Anexos')/CamposChave"/>
   </feed>
  </m:inline>
 </link>
```

In JSON output, the "__deferred" object is sent but an empty "results" array should be instead.
What is being sent:
```
{
    "d":{
        "__metadata":{
            "uri":"http://localhost//AlgoWebPOData/odata.svc/Tabelas(ID='S_Anexos')","type":"OData.Tabela"
        },"Campos":{
            "__deferred":{
                "uri":"Tabelas(ID='S_Anexos')/Campos"
            }
        },"CamposChave":{
            "__deferred":{
                "uri":"Tabelas(ID='S_Anexos')/CamposChave"
            }
        },"ID":"S_Anexos","Descricao":"S_Anexos","Copia":null
    }
}
```

What should be:
```
{
    "d":{
        "__metadata":{
            "uri":"http://localhost//GPC/odata.svc/Tabelas(ID='S_Anexos')","type":"OData.Tabela"
        },"Campos":{
            "__deferred":{
                "uri":"Tabelas(ID='S_Anexos')/Campos"
            }
        },"CamposChave":{
            "results":[

            ]
        },"ID":"S_Anexos","Descricao":"S_Anexos","Copia":null
    }
}
```
This happens for $expand from a single entry or $expand from a set.

**Comment by CyberiaResurrection** [comment]
Thanks for reporting this - my gut says something in the CynicSerialiser is playing up.

When you have a chance, could you poke around there and see if you find any more hints or clues?

**Comment by CyberiaResurrection** [comment]
@cdcampos, can you check to see whether this nonexpansion-when-empty also happens for single-model relations?  I'm guessing that an entry object is inlined instead of a feed object?

**Comment by cdcampos** [comment]
Yes, it also happens with single entry. We should have always an `<inline>` inside the `<link>` and, if $expand is requested, inside that an `<entry>` as you mention.
Instead, when no data is supplied from the provider method (getResource), we get the `<link .../>` only.

**Comment by CyberiaResurrection** [comment]
Thanks for confirming that it happens both on single entries as well as sets.  I think this might need @c-harris' spec-fu.

Digging further, from s6.1.6 of the v3 OData ATOM spec (http://www.odata.org/documentation/odata-version-3-0/atom-format/) - bolding mine
"6.1.6. Inline Content within a metadata:inline Element
An atom:link element describing an OData relationship MAY contain a single metadata:inline element, in which case the element contains the feed (in the case of a collection) or entry (in the case of a single entity), where the feed or entry is a child of the metadata:inline element formatted as per this document.

**An empty metadata:inline element means that there is no content associated with the relationship** (i.e., the navigation property is null). Note that this case is distinct from the absence of a metadata:inline element which simply means that the contents of the relationship is deferred (not included in the payload).

It is valid to include the metadata:inline element in only a subset of the entries within a feed."

Unless I've misread it (which is quite very possible), an empty metadata:inline element would be represented, using your example, as follows:

```
<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/CamposChave" type="application/atom+xml;type=feed" title="CamposChave" href="Tabelas(ID='S_Anexos')/CamposChave">
<m:inline/>
 </link>
```

On JSON side of things (http://www.odata.org/documentation/odata-version-3-0/json-verbose-format/#representingmultipleentitiesinaresponse) - bolding again mine:
"
6.3 Representing Multiple Entities in a Response
In OData 1.0, a collection of entities in a response is formatted just like in a request. See Representing Multiple Entities in a Request for details.

The rest of this section applies to OData 2.0 and 3.0 only.

A collection of entities is represented as in the following example.

{
    "__metadata": { ... },
    "__count": 37,
    "results": [
        { ... },
        { ... },
        { ... }
    ],
    "__next": "/next?$skiptoken=342r89",
}
A collection of entities MUST be represented as a JSON object. This object MUST contain a results name/value pair. It MAY contain __count, __next, or __metadata name/value pairs.

The results value MUST be a JSON array. Each element MUST be a correctly formatted entity (see Representing an Entity).

The __count name/value pair represents the inlinecount. Its value MUST be an integer corresponding to the total count of members in the collection represented by the request. If present, this name/value pair MUST come before the results name/value pair. See $inlinecount for details on when it is required and when it is prohibited.

The __next name/value pair MAY be included. If provided, its value MUST be a string containing a URL. If provided, then the response MUST be interpreted as a partial result. The client MAY request this URL if it wishes to receive the next part of the collection or entity set.

The __metadata name/value pair MAY be included. If provided, its value MUST be a JSON object. This object represents the metadata for the set of entities.

**An empty collection of entities (one that contains no entity type instances) MUST be represented as a JSON object with a results name/value pair. The results name/value pair MUST be an empty JSON array.**

"
I think the JSON example you provided matches that - but again, I may well have misread it.

**Comment by CyberiaResurrection** [comment]
Either way, I think it might be worth spinning up a writeEmptyEntry method in the Cynic serialiser as it's a rather specialised case (compared with an empty feed, which isn't).

**Comment by cdcampos** [comment]
The point is that the response should differentiate the cases where no result exists (empty set or null when single entry) from the cases where no response is provided, the "deferred" case . In my use of POData, with OpenUI5 framework, this is quite relevant, the absence of `<inline>` (or corresponding _deferred in JSON) leads to the frameworks automatically firing single read requests, even if $expand was used in the first instance. On the documentation you cite, in section 6.1.6 of Atom this distinction is acknowledged: "Note that this case is distinct from the absence of a metadata:inline element which simply means that the contents of the relationship is deferred (not included in the payload)."

Reading the odata specs for 3.0 I don't see that this version is different on this topic. So I would expect the output to be the same as it was on versions of POData before 0.3.0 (the ones I mention in my original post above as "correct").

**Comment by CyberiaResurrection** [comment]
We're loudly agreeing that _something_ has to be there (to stop your framework, frinstance, automatically firing single requests), and in local testing I've managed to replicate what you've quoted for an empty feed.

What I've found is that empty-feed and empty-entry cases are different enough that the second case may well need its own method.
 
When I'm more awake, I'll look at entry side of things.

**Comment by CyberiaResurrection** [comment]
Sorry for the delay - life snuck up on me.

I've made changes in #206 that I think has fixed the problem - can you test and see if I've fixed problem or if I only think I have?

**Comment by cdcampos** [comment]
Tested now, for both single and multi-entry navigation's, all working fine. Thanks!!
Closing this issue now.

**Comment by CyberiaResurrection** [comment]
Sweet, thanks for your patience.
