### ISSUE TITLE
undefined method MetadataManager::getResourceSetNameFromResourceType

### ISSUE THREAD

**Issue by NoelDeMartin** [Algo-Web/POData#209]
I am getting an error when the method `getResourceSetNameFromResource` is called in MetadataManager because it doesn't exist. I see this was introduced in commit 6b7e8f2a5c1614a154f8d03ae67c64fff6cbe11b but I don't see the implementation of this method anywhere, so I am not sure how is that possibly working in the tests.

I reverted the commit in my code and it works, but since there is something else going on that I'm not aware of I preferred to open an issue than opening a PR.

**Comment by CyberiaResurrection** [comment]
Noel,

Thanks for downloading POData, trying it out, and opening the issue.  To satisfy my own curiosity, what are you using POData for?

A while ago, we pulled the metadata management stuff out to its own project - here's the MetadataManager you seem to be looking for:
https://github.com/Algo-Web/ODataMetadata/blob/master/src/MetadataManager.php

**Comment by NoelDeMartin** [comment]
@CyberiaResurrection I see, my bad. I forked this project and POData-Laravel and I didn't notice there was a different project for that, so I was working with the edge version of those two and the one I got from packagist for the metadata, hence the mismatch.

As per the reason I am using it, I am working on a protocol to build applications that aren't tied to server implementations, and I want to build it on top of existing protocols as much as possible. For authentication I'll use OAuth, and for the data exchange I am looking at different options like GraphQL, OData, etc. So far OData is the one I like the most but I am concerned about the support and the community :/. I know there was an official package called "OData Producer Library" by Microsoft, but for some reason it seems to have disappeared and I haven't found any official statements as to why. So I am using this library to tinker a bit with OData and see how it feels :D.

In case you're interested to know more, I am documenting it here: [https://noeldemartin.github.io/autonomous-data/](https://noeldemartin.github.io/autonomous-data/) I am still playing with the idea so take it with with a grain of salt. And of course, feedback is always welcome :D.

**Comment by CyberiaResurrection** [comment]
@NoelDeMartin , thanks for the reply and assuaging my curiosity.

I'm not sure if the OData Producer Library was ever actually official, per se - @c-harris could probably give you the full story there.

**Comment by NoelDeMartin** [comment]
I saw this post on the Microsoft blog, so I guess it was official: [https://blogs.msdn.microsoft.com/interoperability/2011/09/09/the-odata-producer-library-for-php-is-here/](https://blogs.msdn.microsoft.com/interoperability/2011/09/09/the-odata-producer-library-for-php-is-here/) But I couldn't find anything else of what happened with it.

**Comment by c-harris** [comment]
G'day Noel,

Sorry I have been a bit out of touch i am in the process of migrating to new system which is taking longer then accepted. We are only a small community here but I am the chief of data guru. If I might address some of your concerns about support for odata I am happy to tell you that so long as you are using our package I will be happy to provide you with any support I can. 

One thing that has some what slowed development is we do not currently have any active (read paying) development jobs using Podeta which slows down the feed back cycle as bugs are found. 

To answer the question with regards "OData Producer Library" that was an official product in the sense that Microsoft dev's did roll it out but not long after they kicked it off it was left to the open source community you could find a copy of that project here

https://github.com/dineshkummarc/odataphpprod/tree/master/library/ODataProducer

And I think the origion it was one of the many projects that we referenced when putting this together any other questions, feel free to let me know.

**Comment by NoelDeMartin** [comment]
My main concern is about the community in general, not only this package. Seems like OData v4 was released back in 2014, so the fact that it's lacking so many resources being 4 years old does not look good :/. But it doesn't seem like there are many alternatives either. GraphQL is the only one that seems to do something similar and it has an active community.
