### ISSUE TITLE
isSingleResult() has issue that is solved outside of function.

### ISSUE THREAD

**Issue by c-harris** [Algo-Web/POData#21]
In src/POData/BaseService.php on lines 358-360 
```php
$method = $this->_serviceHost->getOperationContext()->incomingRequest()->getMethod();
$method = ($method != HTTPRequestMethod::POST());
if (!$request->isSingleResult() && $method) {
```

the checks that are being performed here in the $method variable should be performed inside the isSingleResult function. otherwise it will need to be duplicated at other locations.

**Comment by CyberiaResurrection** [comment]
Obsolete
