### ISSUE TITLE
How to mapping Entity inside a schema

### ISSUE THREAD

**Issue by rivalix** [Algo-Web/POData#214]
I have mapped the Product class that refers to the product table in my database, but my table is contained in a schema, eje: mydatabase.logistic.product.

how can I map in my Product class the reference to logistic.product and not only to product????

Thanks!!

**Comment by CyberiaResurrection** [comment]
@rivalix ,

Great to hear that you're using POData.  As I'm not that good at reading minds, I'll have to ask you to bear with me as I ask a few questions:

1 - Are you using POData directly, or via an adaptor (such as POData-Laravel)?
2 - What DB engine are you using?
3 - Does the current, erroneous, mapping deliver the correct records?

**Comment by rivalix** [comment]
I'm trying using POData directly with sqlserver, want to map the entities of my database but are not in the dbo scheme, they are inside a scheme called logistic (logistic.prouduct).

**Comment by c-harris** [comment]
Only a quick response, you need to implement a custom Iqueryprovider
https://github.com/Algo-Web/POData/blob/master/src/POData/Providers/Query/IQueryProvider.php

You can find a mysql example here
https://github.com/Algo-Web/POData-example
