### ISSUE TITLE
Handling PHP_EOL in IndentedTextWriter::getResult() method

### ISSUE THREAD

**Issue by kirill533** [Algo-Web/POData#240]
Hi!

I dont quite understand how the new version of IndentedTextWriter::getResult() method is supposed to work.

What if the result variable will already include CRLF line endings. In this case, it will be replaced to CRCRLF?

```
    /**
     * @return string the current written text
     *                strReplace as json_encode does not always respect PHP_EOL
     */
    public function getResult()
    {
        return str_replace("\n", PHP_EOL, $this->result);
    }

```

p.s.

But actually, line separators sometimes needs to be adapted to meet the format requirements of some clients. For example, since I integrate with Microsoft products, I might prefer to return CRLF, even though my server runs on Linux.

I have recently integrated the last master version and it worked well after the recent refactoring. Thanks for that! 

I have also noticed that some tests throw errors on windows version, probably because of usage of PHP_EOL. Thats why I started to look into the topic.

**Comment by c-harris** [comment]
You raise a good point with the bug. And end of line has been an issue for us. How do you think we should handle it?

**Comment by c-harris** [comment]
Also I really like some of your changes. Specifically this one 
https://github.com/kirill533/POData/commit/99caf30484e0cd2933e4c7f1e9a5f58f8d3cd61d 

And would welcome a pull request 

@CyberiaResurrection take a look at the referenced commit.

**Comment by kirill533** [comment]
Also, in the method ChangeSetParser::handleData(), does it handle the request from the client? In this case it is not quite logical to expect client to be consistent with our PHP_EOL.

I have tested this implementation and it worked for me well:
```
            $match               = trim($match);
            $match               = str_replace("\r", '', $match); // removes windows specific character
            $lines                  = explode("\n", $match);
```

**Comment by kirill533** [comment]
@c-harris yes, I had to do some modifications to make it working for me. I did the latest merge under https://github.com/kirill533/POData/tree/algomergemaster branch.

I was thinking about pull request, but I do not think, that all of the logic I have added will work for all cases.

I had to modify some output format to match the expectations of Power BI. But those changes introduce a kind of mix of different versions of OData Standard.

**Comment by kirill533** [comment]
The getResult() method I would wrote now this way:
```
    /**
     * @return string the current written text
     *                strReplace as json_encode does not always respect PHP_EOL
     */
    public function getResult()
    {
        return str_replace("\n", \Podata\BaseService::$PHP_EOL, str_replace("\r\n", "\n", $this->result));
    }
```

But this is not the most efficient implementation. 

For me the initial modification of this method seems strange. I guess, there were some reason for it. But it seems like the issue was not fixed in the place where it appeared, but on the highest level.

**Comment by kirill533** [comment]
Before, in the method **writeLine()** you are adding "\n" line ending. And after that you replace line endings in the whole result from "\n" to PHP_EOF. 

Maybe, it was enough to change it in the **writeLine()** method?

You wrote the explanation that "json_encode does not always respect PHP_EOL", but how should it respect it? If you are not doing PRETTY json, should not the output of json_encode be just all in one line?

**Comment by kirill533** [comment]
Also, @c-harris ,
the commit you have referenced in my fork breaks the logic of expanded data items. I have noticed it recently and had to "disable" some tests because of that. 
The expanding of data is a complex and hard topic if you think about performance. But it is doable.

In that "Memory usage optimization" I read the data from the database with unbuffered queries. And the records are retrieved one by one only in the moment of json records writing. (Or something like that... was some time ago already)

**Comment by kirill533** [comment]
What I would add to this library from myself is the functionality to define the structure without the need to declare the php classes:
https://github.com/kirill533/POData/blob/0e5ff120f4f815189165301f985a1b6a15f03971/tests/UnitTests/POData/Facets/WordPress2/WordPressMetadataDynamic.php

This way the library will be very close to possiblity of just taking any MySQL database and presenting its content via OData without the need to modify php code.

**Comment by c-harris** [comment]
@kirill533 your help has been amazing. If you don't mind I'll have a chat to @CyberiaResurrection And see if we can cherry pick some of your commits across 

When we did expanding we focused on speed not memory foot print but I might take another look at it.

Finally, providing structure without classes is doable with a customer imetadataprovider. Rewriting it is on the to do list but I am making some changes to odata metadata at the moment to better facilitate a cleaner hookup.

**Comment by c-harris** [comment]
You can find the work in progress rewrite of the metadata handler here

https://github.com/Algo-Web/ODataMetadata/tree/rewrite

**Comment by kirill533** [comment]
> You can find the work in progress rewrite of the metadata handler here
> 
> https://github.com/Algo-Web/ODataMetadata/tree/rewrite

Thanks. Quite interesting.

**Comment by kirill533** [comment]
Desided to improve it this way:
https://github.com/kirill533/POData/commit/ea0b055d9617a831380fbb590337c713b49ac2b6

**Comment by kirill533** [comment]
Tried to test the rewrite branch from ODataMetadata, but it is not compatible with latest POData 
(no MetadataManager class :-)

**Comment by c-harris** [comment]
@kirill533 You are correct I'm dropping the metadata manager class and removing JMS as the serialization engine (it was big and slow). I'll be kicking the current job of the metadata manager over to the IMetadataProvider. It will allow more direct and easy cross version usage. It will also allow more complete usage. I'm just working out the annotations then I'll send up a matching branch for podata. Want me to let you know when it's up?

**Comment by kirill533** [comment]
That would be great. I have noticed how long it takes to generate the
metadata schema. Though in most of cases the schema might be cached.

But for simplifying maintenance and development this would be a grate
improvement. I had a headache when I was seeing all those yml files :)

Thank you for keeping the development going on. I checked lot of options
and your library was the best for OData integration.

What is difficult for me is to keep it easily integrated. It would be
easier if number of dependencies will be reduced. The serializer was one of
them. And second is Illuminate\Http\Request . At now it does not allow it
to be installed on a system that have symfony packages of different
versions. Because of that I have asked a freelancer to remove that
dependency for me.

**Comment by c-harris** [comment]
@kirill533 it's funny that you should mention that because it was only earlier today I was talking to @CyberiaResurrection about stripping it out and replacing it with psr/http-message I was planning on getting cracking on that in the near future.

That said if you have specific requests I am happy to take on freelance work (covid-19 has had an impact) no pressure and I'm happy to keep working and helping out in my free time but that is an option because I am already rather up to date with the code base.

**Comment by c-harris** [comment]
@kirill533 pull Request #244 should address your original issue and i have opened up new issues for the other things you brought up. can you take a look and check it handles the new line matters in a way you would find satisfactory?

**Comment by kirill533** [comment]
Hi @c-harris , Sure, it does. Seems like a lot of changes, but I got the idea. Thanks. The getResult method looks better now, for sure. Glad to see, the "prettyPrint" can be disabled now completelly, so that less data will be sent.
The "Dependency Hell" issue is much appreciated! I think, it should improve the stability overall and allow more people to easily integrate the library.

**Comment by c-harris** [comment]
Well the General concept is that you can now pass a [IServiceConfiguration](https://github.com/Algo-Web/POData/blob/master/src/POData/Configuration/IServiceConfiguration.php) to the [BaseService](https://github.com/Algo-Web/POData/blob/master/src/POData/BaseService.php) which includes some extra configs. still needs some cleanup but ill get that merged up sometime this week

**Comment by c-harris** [comment]
Ok we are merging up #244 shortly can you check it sorts out all your new line issues and if so close this issue?

**Comment by kirill533** [comment]
I would also add there the tests with @dataProvider getEOL() as in https://github.com/kirill533/POData/commit/ea0b055d9617a831380fbb590337c713b49ac2b6

I could also take those tests from my version. But I do not know how can I configure the EOL value inside tests with IServiceConfiguration. I was doing it this way: `IndentedTextWriter::$PHP_EOL = $eol;`

Anyway, I will wait for it to be merged.

**Comment by c-harris** [comment]
to use it you would just go
```php
$config = new POData\Configuration\ServiceConfiguration(metadataProvider);
$config->setLineEndings("\n");
$service = new BaseService($queryProvider, $metadataProvider, $host, $config);
```

We have merged it up and ill look at borrowing your tests in the near future

**Comment by kirill533** [comment]
@c-harris ,

I would appreciate if we also find a concensus on ChangeSetParser::handleData() method:

https://github.com/Algo-Web/POData/issues/240#issuecomment-623707325

The point is that if this method will process the request comming from the client, we should support both types of line endings in here.

I have fixed it while ago and I think, it would be good to include this modification in the library.

**Comment by c-harris** [comment]
Sorry @kirill533 I over looked that one. I have stepped away from the computer to spend some time with my partner.

I'll add you suggest change to the inbound requests handling.

For response would you be happy with using the configured EOL?

**Comment by c-harris** [comment]
@kirill533 I went to make the changes to the change set parsers and well it was a mess. It was bashed out in a hurry so I have set myself at fixing it. 

Is batch processing somthing you are up to speed with? (The documentation on the topic is sparse)

Would you mind if I ask you to review the PR when it comes up and/or provide some tests?

**Comment by kirill533** [comment]
No, I guess, I never tested/used the "batch processing".
But for some reason I did change the ChangeSetParser::handleData(). Maybe, it is used not only in batch processing? If not so, I might have changed that trying to fix some errors and end up fixing it somewhere else.

**Comment by kirill533** [comment]
I have made some tests for EOL. Want to create pull request based on that. Just need to find time for that.

**Comment by kirill533** [comment]
And only one small commend towards that. I saw you made the default value for the pretty print to be dependent on php error_reporting settings somewhere.
I would discourage from doing that because often dev/test server may have that setting different from productive env. So, it makes the pre-production testing less reliable. It may also be not transparent for those who will be debugging the output and will start wondering, why json looks differently.
I would just put it to pretty by default.

**Comment by c-harris** [comment]
I'll send that up shortly. I think that's a good call and ill just default it to true. I look forward to your Pr even if the tests fail I'll get to work fixing them. Thanks heaps. Again for helping through this.

**Comment by c-harris** [comment]
@kirill533 are you right to close this issue? I believe the original problem has been addressed and other notes have been mined into separate issues.
