### ISSUE TITLE
Dependency Hell

### ISSUE THREAD

**Issue by c-harris** [Algo-Web/POData#243]
The wealth of information provided at #240 has identified that we have some major dependency issues that we could probably work around/avoid. firstly we have pulled in entire packages to access a tiny amount of it. secondly we have oddly specific dependencies. Finally we are using namespaces that we don't have dependencies for and praying they get pulled in at the second level. Audit and clean is required

**Comment by c-harris** [comment]
@kirill533 pull request #246 let's the foundation for the removal of illuminate/http Which all things considered we should be able to wack on the head but I would like to ask, for your integration what are you doing for operation context?

**Comment by kirill533** [comment]
Thank you, @c-harris , I have build a BI solution for Magento system, integrating Magento with Power BI:
https://www.bimproject.net/en/products/extensions-for-magento/power-bi-integration.html
Most of the functionality is based on usage of Power BI REST API without usage of OData. 
OData comes as an alternative way of integration with its own pros and cons.

So, basically, the library ends up being integrated into Magento.

**Comment by c-harris** [comment]
@kirill533 i think you misunderstood my question, I was wondering what you are passing to [ServiceHost::__construct](https://github.com/Algo-Web/POData/blob/master/src/POData/OperationContext/ServiceHost.php#L93)

**Comment by kirill533** [comment]
I have just checked the code. I am extending almost all of the major classes. I have removed comments from there and placed the code related to OperationContextAdapter below.

This is how I am calling it all:

```
            $request = new IncomingRequest(
                $requestUri,
                $headers
            );
            // Controller
            $op = new OperationContextAdapter($request);

            $host = new ServiceHost($op);

            $host->setServiceUri($baseUrl);
            /** @var \BimLib\PbiOdata\Model\QueryProviderFactory $queryProviderFactory */
            $queryProviderFactory = PbiOdata::getModuleInstance()->getFactoryManager()
                ->getModelInstance(\BimLib\PbiOdata\Model\Factory::MODEL_QUERY_PROVIDER_FACTORY);

            $queryProvider = $queryProviderFactory->createQueryProvider($datasetId);

            $metadataProvider = new MetadataProvider('MagentoEntities', $datasetId);

            $service = new BaseService($queryProvider, $metadataProvider, $host);

            $service->handleRequest();
            $odataResponse = $op->outgoingResponse();

```

**IncomingRequest:**

```
<?php
namespace BimLib\PbiOdata\Podata;

use POData\OperationContext\IHTTPRequest;

class IncomingRequest
    extends \POData\OperationContext\Web\IncomingRequest
    implements IHTTPRequest
{
    protected $bimMethod;
    protected $requestUri;
    protected $bimHeaders;
    protected $bimQueryOptions;
    protected $bimQueryOptionsCount;

    public function __construct($requestUri, $headers)
    {
        $this->requestUri = $requestUri;
        $this->bimHeaders = array_combine(array_map('strtolower', array_keys($headers)),  $headers);

        $this->bimMethod = 'GET';
        $this->bimQueryOptions = [];
        $this->bimQueryOptionsCount = [];
    }

    /**
     * @return mixed
     */
    public function getRawUrl()
    {
        return strtok($this->requestUri, '?');
    }

    function getRequestHeader($key)
    {
        $key = strtolower($key);
        return isset($this->bimHeaders[$key]) ? $this->bimHeaders[$key] : null;
    }

    public function getMethod()
    {
        return $this->bimMethod;
    }

    public function getQueryParameters()
    {
        if (0 == count($this->bimQueryOptions)) {
            $queryString = $this->getBimQueryString();
            $this->bimQueryOptions = [];

            foreach (explode('&', $queryString) as $queryOptionAsString) {
                $queryOptionAsString = trim($queryOptionAsString);
                if (!empty($queryOptionAsString)) {
                    $result = explode('=', $queryOptionAsString, 2);
                    $isNamedOptions = 2 == count($result);
                    $rawUrl = rawurldecode($result[0]);
                    if ($isNamedOptions) {
                        $this->bimQueryOptions[] = [$rawUrl => trim(rawurldecode($result[1]))];
                    } else {
                        $this->bimQueryOptions[] = [null => trim($rawUrl)];
                    }
                }
            }
        }

        return $this->bimQueryOptions;
    }

    private function getBimQueryString()
    {
        return parse_url($this->requestUri, PHP_URL_QUERY);
    }
}
```

**OperationContextAdapter**
```
<?php
namespace BimLib\PbiOdata\Podata;

use POData\OperationContext\Web\OutgoingResponse;

class OperationContextAdapter
implements \POData\OperationContext\IOperationContext
{
    protected $incomingRequest;
    protected $outgoingResponse;

    public function __construct(IncomingRequest $request)
    {
        $this->incomingRequest = $request;
        $this->outgoingResponse = new OutgoingResponse();
    }

    public function outgoingResponse()
    {
        return $this->outgoingResponse;
    }

    public function incomingRequest()
    {
        return $this->incomingRequest;
    }
}
```


**ServiceHost:**
```
<?php
namespace BimLib\PbiOdata\Podata;

class ServiceHost extends \POData\OperationContext\ServiceHost
{
    function __construct(\POData\OperationContext\IOperationContext $context)
    {
        $incomingRequest = new \Illuminate\Http\Request();
        parent::__construct($context, $incomingRequest);
    }
}
```

**Comment by kirill533** [comment]
I have just realized, that I probably did not even use the Illuminate\Http\Request in my initial implementation.
I supply it to ServiceHost just because it lists it as input parameter. But it is not even used if I supply my own IOperationContext.

**Comment by c-harris** [comment]
you are correct, that was a bug that got introduces i don't know how. the [IlluminateOperationContext](https://github.com/Algo-Web/POData/blob/master/src/POData/OperationContext/Web/Illuminate/IlluminateOperationContext.php) really should be a part of [POData-Laravel](https://github.com/Algo-Web/POData-Laravel) but some how it ended up here. the open pull request there to isolate it and move it to where it should be.

 that will remove illuminate as a dependency here. and it was also a dependency on [ODataMetadata](https://github.com/Algo-Web/ODataMetadata) but i have removed it there as well. this will hopefully make it easier for you to maintain integration

**Comment by c-harris** [comment]
@kirill533 there is a new 0.1.3 version of ODataMetadata that trims its dependacy tree a lot. We have cut master here over to have it as a min as it greatly speeds composer to not consider lower versions.

I mention it because I know you are maintaining your own fork of that and thought you might want to bring those changes across.

**Comment by CyberiaResurrection** [comment]
I've created an issue on OData to prompt finishing the overall cleanup - https://github.com/Algo-Web/ODataMetadata/issues/153

There's not much more, if any, to do inside POData itself.
