### ISSUE TITLE
Lack of input checking

### ISSUE THREAD

**Issue by c-harris** [Algo-Web/POData#25]
we really should be checking the names when they are being set to propertys to make sure they only contain underscores.
https://github.com/c-harris/POData/blob/master/src/POData/Providers/Metadata/ResourceProperty.php

**Comment by CyberiaResurrection** [comment]
Fixed by https://github.com/Algo-Web/POData/commit/2a3e8802887b5e0254f722f7fae3e5b3fe4aed70
