### ISSUE TITLE
Edm.DateTime is not written according to OData Json specs  

### ISSUE THREAD

**Issue by cdcampos** [Algo-Web/POData#50]
Currently JsonWriter.php produces a Edm.DateTime in format "yyyy-mm-ddThh:mm:ss" which does not comply with OData Json specs in http://www.odata.org/documentation/odata-version-2-0/json-format/

> Edm.DateTime

	"/Date(<ticks>["+" | "-" <offset>)/"<ticks> = number of milliseconds since midnight Jan 1, 1970<offset> = number of minutes to add or subtract

**Comment by CyberiaResurrection** [comment]
@cdcampos , thanks heaps for pointing this out.  Does pull request #51 fix it?

Since php's underlying 'U' date format option returns seconds since Unix epoch, I've taken simplest way out and simply multiplied result by 1000 to convert to milliseconds since epoch.

**Comment by cdcampos** [comment]
And thanks for being so fast!

Result should be in the form "/Date(1486125004000)/"

So, I think you just need to precede the number with "/Date(" and append ")/" after. Then it should be fine :)

**Comment by c-harris** [comment]
@cdcampos Thanks for tracking it down for us, Json is not something we are currently using in our projects which sadly means they get a bit neglected, but if you come across any other issues feel free to let us know. hopefully we will have that pull request updated shortly 👍

**Comment by CyberiaResurrection** [comment]
@cdcampos, pull req #51 should be updated now - can you double-check my change?

**Comment by cdcampos** [comment]
Yes, its working fine :thumbsup:

**Comment by CyberiaResurrection** [comment]
Beaut, thanks for your time and feedback.  Original reporter @cdcampos is happy and has verified fix, so closing issue.

@cdcampos, as @c-harris said, if you've got any more bug reports, keep 'em coming.
