### ISSUE TITLE
Request with $expand of a set ends with fatal error

### ISSUE THREAD

**Issue by cdcampos** [Algo-Web/POData#66]
Issuing a request with $expand of a resource set (1:n) like this:
http://localhost/NorthWind.svc/Customers(‘ALFKI’)?$expand=Orders

Ends with fatal error in line 378 of RequestExpander:

> <b>Fatal error</b>:  Uncaught Error: Call to undefined method Closure::getReference() in /www/GEA/vendor/algo-web/podata/src/POData/UriProcessor/RequestExpander.php:378

Taking out ...->getReference() works fine, apparently:
`$orderByFunction = $internalOrderByInfo->getSorterFunction();`

**Comment by CyberiaResurrection** [comment]
Thanks heaps for reporting this.

Looking at coverage results, Dread Finagle Strikes Back - you've tripped over one of the two uncovered bits of RequestExpander.

Let me see what I can wring out.

**Comment by CyberiaResurrection** [comment]
Ok, I think that's fixed it - per both your suggestion and tests.  Can you grab latest version and see if pain still persists?

**Comment by cdcampos** [comment]
Yes, fixed. Thanks!
