### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by kingschnulli** [Algo-Web/POData#73]
Is this still maintained? Will there be releases?

**Comment by c-harris** [comment]
Feel the city breakin' and everybody shakin'
And we're stayin' alive, stayin' alive

But seriously yes it is still alive, and still maintained, we have been working on a major rewrite of the metadata framework which will probably result in a version bump, we will probably also be extending to V4 support soon. 

At the moment we have 3 releases with a major one coming after the metadata rewrite is finished.

most people use our [laravel plugin](https://github.com/Algo-Web/POData-Laravel) but if you need any help hooking up with your own solution just let us know.

**Comment by CyberiaResurrection** [comment]
DIsproven by recent activity, so off you go.
