### ISSUE TITLE
Someone removed all convenience for the sake of complexity

### ISSUE THREAD

**Issue by c-harris** [Algo-Web/POData#88]
There are large parts of the code base that were based on poor design concepts from time immemorial. i think this has dragged POData progress for many many years. 

As the lead design team have reviewed we have decided a need exists to rewrite large parts of the existing code base to make better use of composer packages and to make the code base a lot simpler.  major components to review should be: 
UriProcessor
Writers
Providers
and
ObjectModel

**Comment by CyberiaResurrection** [comment]
The UriProcessor and ObjectModelSerialiser have been dropped out in favour of saner, cleaner, smaller, less complex rewrites.
